// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!|QQOPOOOOOO'#C_'#C_OOOO'#Cb'#CbOcOPO'#C`OcOPO'#C^OOOO'#Cd'#CdOOOO'#Ca'#CaQQOPOOOOOO-E6`-E6`OOOO'#Ci'#CiOOOO,58z,58zOcOPO,58xOOOO,58x,58xOOOO-E6_-E6_OOOO1G.d1G.d",
  stateData: "n~OXPOYPOZPO[QO^TO~O[QO^XO_XO~O",
  goto: "!V^PP_c_gmPxPPPP|TTOVTSOVQVOR]VSROVSWRZRZSTUOVQYRQ[SR^Z",
  nodeNames: "⚠ Content CommandLine Checkbox CommentLine",
  maxTerm: 15,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "#k~RWOYkYZpZ]k]^p^qkqr{r~k~~#f~pO[~~uQ^~YZp]^p~!QP[~!}#O!T~!WRpq!a#c#d!r#l#m#T~!dP#P#Q!g~!jPqr!m~!rOX~~!uP#P#Q!x~!{Pqr#O~#TOY~~#WP#P#Q#Z~#^Pqr#a~#fOZ~~#kO_~",
  tokenizers: [0],
  topRules: {"Content":[0,1]},
  tokenPrec: 0
})

