// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$OQQOPOOOOOO'#Cg'#CgO]OPO'#CeOhOPO'#C^OOOO'#Ci'#CiOmOPO'#CiOOOO'#Cf'#CfQQOPOOOOOO-E6e-E6eOuOPO'#C`O}OPO,58xOOOO'#Cv'#CvOOOO,59T,59TOOOO-E6d-E6dO!tOQO1G.dOOOO'#Cc'#CcOOOO'#Cd'#CdO!{OQO'#CbOOOO'#Ca'#CaOOOO7+$O7+$OO!SOQO7+$OOOOO,58|,58|OOOO<<Gj<<Gj",
  stateData: "#W~ORRO^POkSO~O^POkXXlXX~O^PO~OkZOlZO~O^PORSX~OR^O~O`_Oa_Ob_Oc_Od_Oe`Of`Og`Oh`Oi`O~O_dO~P!SO_eOkZOlZO~O",
  goto: "!rkPPlPpsy}}!R!V!]P!hPPPPPPPPPPPP!lTSOVRYRQc^RfdTb^dTa^dTTOVQVOR]VSQOVSWQXRXRTUOVQ[TRea",
  nodeNames: "⚠ Content Property = PropertyName PropertyValue BooleanValue True False Plaintext",
  maxTerm: 28,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "'S~RlOX!yXY#OYZ#hZ]!y]^#h^p!ypq#Oq!_!y!_!`#s!`!h!y!h!i#x!i!p!y!p!q$P!q!v!y!v!w$W!w!{!y!{!|$_!|#Y!y#Y#Z$f#Z#b!y#b#c%V#c#d%d#d#h!y#h#i&P#i#m!y#m#n&j#n~!y~~&}P#OO^PR#VQ^P_QXY#]pq#]Q#bQ_QXY#]pq#]~#mQk~YZ#h]^#h~#xOR~R$POhQ^PR$WOiQ^PR$_OcQ^PR$fOdQ^PR$kP^P#T#U$nQ$qP#`#a$tQ$wP#g#h$zQ$}P#X#Y%QQ%VOeQR%[P^P#c#d%_Q%dOfQR%iQ^P#Y#Z%o#b#c%zQ%rP#Y#Z%uQ%zOgQQ&PObQR&UP^P#f#g&XQ&[P#i#j&_Q&bP#X#Y&eQ&jO`QR&oP^P#X#Y&rQ&uP#g#h&xQ&}OaQ~'SOl~",
  tokenizers: [0, 1],
  topRules: {"Content":[0,1]},
  tokenPrec: 0
})

